namespace aplicacion.Models
{
    public class ConstantsAndList
    {
        public List<string> ListComunas { get; set; } = new List<string>
        {
            "ARICA",
            "IQUIQUE",
            "HUARA",
            "PICA",
            "POZO ALMONTE",
            "TOCOPILLA",
            "ANTOFAGASTA",
            "MEJILLONES",
            "TALTAL",
            "CALAMA",
            "CHANARAL",
            "DIEGO DE ALMAGRO",
            "COPIAPO",
            "CALDERA",
            "TIERRA AMARILLA",
            "VALLENAR",
            "FREIRINA",
            "HUASCO",
            "LA SERENA",
            "LA HIGUERA",
            "COQUIMBO",
            "ANDACOLLO",
            "VICUNA",
            "PAIHUANO",
            "OVALLE",
            "MONTE PATRIA",
            "PUNITAQUI",
            "RIO HURTADO",
            "COMBARBALA",
            "ILLAPEL",
            "CANELA",
            "SALAMANCA",
            "LOS VILOS",
            "VALPARAISO",
            "QUINTERO",
            "PUCHUNCAVI",
            "VINA DEL MAR",
            "QUILPUE",
            "VILLA ALEMANA",
            "CASABLANCA",
            "ISLA DE PASCUA",
            "SAN ANTONIO",
            "SANTO DOMINGO",
            "ALGARROBO",
            "EL QUISCO",
            "CARTAGENA",
            "EL TABO",
            "QUILLOTA",
            "LA CRUZ",
            "LA CALERA",
            "HIJUELAS",
            "NOGALES",
            "LIMACHE",
            "OLMUE",
            "PETORCA",
            "CABILDO",
            "PAPUDO",
            "ZAPALLAR",
            "LA LIGUA",
            "SAN FELIPE",
            "PUTAENDO",
            "PANQUEHUE",
            "CATEMU",
            "SANTA MARIA",
            "LLAY-LLAY",
            "LOS ANDES",
            "CALLE LARGA",
            "RINCONADA",
            "SAN ESTEBAN",
            "SANTIAGO",
            "LAS CONDES",
            "PROVIDENCIA",
            "SANTIAGO OESTE",
            "CONCHALI",
            "COLINA",
            "RENCA",
            "LAMPA",
            "QUILICURA",
            "TIL-TIL",
            "QUINTA NORMAL",
            "PUDAHUEL",
            "CURACAVI",
            "SANTIAGO SUR",
            "PENAFLOR",
            "TALAGANTE",
            "ISLA DE MAIPO",
            "MELIPILLA",
            "EL MONTE",
            "MARIA PINTO",
            "NUNOA",
            "LA REINA",
            "LA FLORIDA",
            "MAIPU",
            "SAN MIGUEL",
            "LA CISTERNA",
            "LA GRANJA",
            "SAN BERNARDO",
            "CALERA DE TANGO",
            "PUENTE ALTO",
            "PIRQUE",
            "SAN JOSE DE MAIPO",
            "BUIN",
            "PAINE",
            "RANCAGUA",
            "MACHALI",
            "GRANEROS",
            "SAN PEDRO",
            "ALHUE",
            "CODEGUA",
            "SAN FRANCISCO DE MOSTAZAL",
            "DONIHUE",
            "COLTAUCO",
            "COINCO",
            "PEUMO",
            "LAS CABRAS",
            "SAN VICENTE",
            "PICHIDEGUA",
            "REQUINOA",
            "OLIVAR",
            "RENGO",
            "MALLOA",
            "QUINTA DE TILCOCO",
            "SAN FERNANDO",
            "CHIMBARONGO",
            "NANCAGUA",
            "PLACILLA",
            "SANTA CRUZ",
            "LOLOL",
            "PALMILLA",
            "PERALILLO",
            "CHEPICA",
            "PAREDONES",
            "MARCHIGUE",
            "PUMANQUE",
            "LITUECHE",
            "PICHILEMU",
            "NAVIDAD",
            "LA ESTRELLA",
            "CURICO",
            "ROMERAL",
            "TENO",
            "RAUCO",
            "HUALANE",
            "LICANTEN",
            "VICHUQUEN",
            "MOLINA",
            "SAGRADA FAMILIA",
            "RIO CLARO",
            "TALCA",
            "SAN CLEMENTE",
            "PELARCO",
            "PENCAHUE",
            "MAULE",
            "CUREPTO",
            "SAN JAVIER",
            "CONSTITUCION",
            "EMPEDRADO",
            "LINARES",
            "YERBAS BUENAS",
            "COLBUN",
            "LONGAVI",
            "VILLA ALEGRE",
            "PARRAL",
            "RETIRO",
            "CAUQUENES",
            "CHANCO",
            "CHILLAN",
            "PINTO",
            "COIHUECO",
            "PORTEZUELO",
            "QUIRIHUE",
            "TREHUACO",
            "NINHUE",
            "COBQUECURA",
            "SAN CARLOS",
            "NIQUEN",
            "SAN FABIAN",
            "SAN NICOLAS",
            "BULNES",
            "SAN IGNACIO",
            "QUILLON",
            "YUNGAY",
            "PEMUCO",
            "EL CARMEN",
            "COELEMU",
            "RANQUIL",
            "CONCEPCION",
            "TALCAHUANO",
            "TOME",
            "PENCO",
            "HUALQUI",
            "FLORIDA",
            "CORONEL",
            "LOTA",
            "SANTA JUANA",
            "CURANILAHUE",
            "ARAUCO",
            "LEBU",
            "LOS ALAMOS",
            "CANETE",
            "CONTULMO",
            "TIRUA",
            "LOS ANGELES",
            "SANTA BARBARA",
            "QUILLECO",
            "YUMBEL",
            "CABRERO",
            "TUCAPEL",
            "LAJA",
            "SAN ROSENDO",
            "NACIMIENTO",
            "NEGRETE",
            "MULCHEN",
            "QUILACO",
            "ANGOL",
            "PUREN",
            "LOS SAUCES",
            "RENAICO",
            "COLLIPULLI",
            "ERCILLA",
            "TRAIGUEN",
            "LUMACO",
            "VICTORIA",
            "CURACAUTIN",
            "LONQUIMAY",
            "TEMUCO",
            "VILCUN",
            "FREIRE",
            "CUNCO",
            "LAUTARO",
            "GALVARINO",
            "PERQUENCO",
            "NUEVA IMPERIAL",
            "CARAHUE",
            "SAAVEDRA",
            "PITRUFQUEN",
            "GORBEA",
            "TOLTEN",
            "LONCOCHE",
            "VILLARRICA",
            "PUCON",
            "VALDIVIA",
            "CORRAL",
            "MARIQUINA",
            "MAFIL",
            "LOS LAGOS",
            "FUTRONO",
            "LANCO",
            "PANGUIPULLI",
            "LA UNION",
            "PAILLACO",
            "RIO BUENO",
            "LAGO RANCO",
            "OSORNO",
            "PUYEHUE",
            "SAN PABLO",
            "PUERTO OCTAY",
            "RIO NEGRO",
            "PURRANQUE",
            "PUERTO MONTT",
            "COCHAMO",
            "MAULLIN",
            "LOS MUERMOS",
            "CALBUCO",
            "PUERTO VARAS",
            "LLANQUIHUE",
            "FRESIA",
            "FRUTILLAR",
            "CASTRO",
            "CHONCHI",
            "QUEILEN",
            "QUELLON",
            "PUQUELDON",
            "QUINCHAO",
            "CURACO DE VELEZ",
            "ANCUD",
            "QUEMCHI",
            "DALCAHUE",
            "CHAITEN",
            "FUTALEUFU",
            "PALENA",
            "COYHAIQUE",
            "AYSEN",
            "CISNES",
            "CHILE CHICO",
            "RIO IBANEZ",
            "COCHRANE",
            "PUNTA ARENAS",
            "NATALES",
            "PORVENIR",
            "GENERAL LAGOS",
            "PUTRE",
            "CAMARONES",
            "CAMINA",
            "COLCHANE",
            "MARIA ELENA",
            "SIERRA GORDA",
            "OLLAGUE",
            "SAN PEDRO DE ATACAMA",
            "ALTO DEL CARMEN",
            "ANTUCO",
            "MELIPEUCO",
            "CURARREHUE",
            "TEODORO SCHMIDT",
            "SAN JUAN DE LA COSTA",
            "HUALAIHUE",
            "GUAITECAS",
            "OHIGGINS",
            "TORTEL",
            "LAGO VERDE",
            "TORRES DEL PAINE",
            "RIO VERDE",
            "SAN GREGORIO",
            "LAGUNA BLANCA",
            "PRIMAVERA",
            "TIMAUKEL",
            "CABO DE HORNOS",
            "PELLUHUE",
            "JUAN FERNANDEZ",
            "PENALOLEN",
            "MACUL",
            "CERRO NAVIA",
            "LO PRADO",
            "SAN RAMON",
            "LA PINTANA",
            "ESTACION CENTRAL",
            "RECOLETA",
            "INDEPENDENCIA",
            "VITACURA",
            "LO BARNECHEA",
            "CERRILLOS",
            "HUECHURABA",
            "SAN JOAQUIN",
            "PEDRO AGUIRRE CERDA",
            "LO ESPEJO",
            "EL BOSQUE",
            "PADRE HURTADO",
            "CONCON",
            "SAN RAFAEL",
            "CHILLAN VIEJO",
            "SAN PEDRO DE LA PAZ",
            "CHIGUAYANTE",
            "PADRE LAS CASAS",
            "HUALPEN",
            "ALTO HOSPICIO",
            "CHOLCHOL",
            "ALTO BIOBIO"
        };
    }
}
